package com.monitor.model;

import java.time.Instant;
import java.util.UUID;

/**
 * Immutable metadata attached to every event as it enters the ingestion pipeline.
 *
 * <p>Keeping transport details (source, correlation ID, replay flag) out of
 * {@link UnifiedEvent} preserves the domain model's purity and allows the same
 * event record to be ingested from different sources without mutation.</p>
 *
 * @param source        identifies which collector submitted the event
 *                      (e.g. {@code "kafka-cdc"}, {@code "infrastructure-poller"})
 * @param receivedAt    wall-clock time at which Monitor received the event
 * @param correlationId unique ID for end-to-end tracing; generated by the producer
 *                      or assigned by Monitor on arrival
 * @param replay        {@code true} when the event is being re-ingested from the
 *                      {@link com.monitor.service.CriticalOutbox} rather than arriving
 *                      fresh from a collector
 */
public record IngestMetadata(
        String source,
        Instant receivedAt,
        String correlationId,
        boolean replay
) {

    /**
     * Creates metadata for a live (non-replay) event arriving from the named source.
     * A random UUID is assigned as the correlation ID.
     *
     * @param source the collector or system that produced the event
     * @return a fresh {@code IngestMetadata} instance
     */
    public static IngestMetadata live(String source) {
        return new IngestMetadata(source, Instant.now(), UUID.randomUUID().toString(), false);
    }

    /**
     * Creates metadata for a replayed event with a known correlation ID.
     * Used when re-delivering a persisted critical event from the outbox.
     *
     * @param source        the original collector identifier
     * @param correlationId the correlation ID preserved from the original ingestion
     * @return a replay {@code IngestMetadata} instance
     */
    public static IngestMetadata replay(String source, String correlationId) {
        return new IngestMetadata(source, Instant.now(), correlationId, true);
    }
}
