CREATE SEQUENCE CRITICAL_OUTBOX_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE CRITICAL_OUTBOX (
    ID NUMBER(19) NOT NULL,
    EVENT_TYPE VARCHAR2(64 CHAR) NOT NULL,
    SEVERITY VARCHAR2(32 CHAR) NOT NULL,
    EVENT_SOURCE VARCHAR2(255 CHAR) NOT NULL,
    EVENT_MESSAGE VARCHAR2(2000 CHAR) NOT NULL,
    EVENT_TIMESTAMP TIMESTAMP(6) NOT NULL,
    ATTEMPTS NUMBER(10) DEFAULT 0 NOT NULL,
    CREATED_AT TIMESTAMP(6) NOT NULL,
    NEXT_ATTEMPT_AT TIMESTAMP(6) NOT NULL,
    DELIVERED NUMBER(1) DEFAULT 0 NOT NULL,
    LAST_ERROR VARCHAR2(1000 CHAR),
    ROW_VERSION NUMBER(19) DEFAULT 0 NOT NULL,
    CONSTRAINT PK_CRITICAL_OUTBOX PRIMARY KEY (ID)
);

CREATE INDEX IDX_CRITICAL_OUTBOX_DUE ON CRITICAL_OUTBOX (DELIVERED, NEXT_ATTEMPT_AT);
CREATE INDEX IDX_CRITICAL_OUTBOX_REPLAY ON CRITICAL_OUTBOX (ID);

