-- =============================================================================
-- Monitor Dashboard – Oracle XE 21c Initialisation Script
-- =============================================================================

-- Enable ARCHIVELOG mode for Debezium
SHUTDOWN IMMEDIATE;
STARTUP MOUNT;
ALTER DATABASE ARCHIVELOG;
ALTER DATABASE OPEN;

-- Supplemental logging
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA;
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

-- Create application user (Hardcoded for local dev stability)
-- Using values from standard .env
CREATE USER monitor_app IDENTIFIED BY "monitor_password"
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP
    QUOTA UNLIMITED ON USERS;

GRANT CONNECT, RESOURCE, CREATE TABLE TO monitor_app;

-- LogMiner privileges for Debezium
GRANT SELECT ANY TRANSACTION TO monitor_app;
GRANT LOGMINING TO monitor_app;
GRANT CREATE SESSION TO monitor_app;
GRANT SELECT ON SYS.V_$DATABASE TO monitor_app;
GRANT SELECT ON SYS.V_$LOG TO monitor_app;
GRANT SELECT ON SYS.V_$LOGFILE TO monitor_app;
GRANT SELECT ON SYS.V_$LOGMNR_CONTENTS TO monitor_app;
GRANT SELECT ON SYS.V_$ARCHIVED_LOG TO monitor_app;
GRANT SELECT ON SYS.V_$TRANSACTION TO monitor_app;

-- Switch to the application schema
ALTER SESSION SET CURRENT_SCHEMA = monitor_app;

-- =============================================================================
-- Table: LOG_TRAZA
-- =============================================================================
CREATE TABLE monitor_app.log_traza (
    id          NUMBER          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    error_code  VARCHAR2(50)    NOT NULL,
    error_msg   VARCHAR2(4000)  NOT NULL,
    severity    VARCHAR2(10)    DEFAULT 'INFO'
                                CHECK (severity IN ('INFO', 'WARNING', 'CRITICAL')),
    source_app  VARCHAR2(100),
    created_at  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- =============================================================================
-- Table: CRITICAL_OUTBOX
-- =============================================================================
CREATE TABLE monitor_app.critical_outbox (
    id              NUMBER          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempts        NUMBER          DEFAULT 0 NOT NULL,
    created_at      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    delivered       NUMBER(1)       DEFAULT 0 NOT NULL,
    event_timestamp TIMESTAMP       NOT NULL,
    event_type      VARCHAR2(50)    NOT NULL,
    last_error      VARCHAR2(4000),
    event_message   VARCHAR2(4000)  NOT NULL,
    next_attempt_at TIMESTAMP       NOT NULL,
    row_version     NUMBER          DEFAULT 0 NOT NULL,
    severity        VARCHAR2(20)    NOT NULL,
    event_source    VARCHAR2(100)   NOT NULL,
    status          VARCHAR2(32)    DEFAULT 'PENDING' NOT NULL,
    last_status_change_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_outbox_status CHECK (status IN ('PENDING', 'PROCESSING', 'DELIVERED'))
);

-- Enable row-level supplemental logging
ALTER TABLE monitor_app.log_traza ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
ALTER TABLE monitor_app.critical_outbox ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

-- Seed data
INSERT INTO monitor_app.log_traza (error_code, error_msg, severity, source_app)
VALUES ('APP-001', 'Scheduled job completed successfully', 'INFO', 'batch-processor');

INSERT INTO monitor_app.log_traza (error_code, error_msg, severity, source_app)
VALUES ('APP-002', 'Connection pool near capacity (85%)', 'WARNING', 'api-gateway');

INSERT INTO monitor_app.log_traza (error_code, error_msg, severity, source_app)
VALUES ('APP-003', 'Unable to reach secondary Oracle node', 'CRITICAL', 'data-sync-daemon');

COMMIT;
