-- =============================================================================
-- Monitor Dashboard – Oracle XE 11g Initialisation Script
-- =============================================================================
-- This script is executed by the gvenzl/oracle-xe image entrypoint when the
-- container starts for the first time.  It runs as SYSDBA (the superuser that
-- already holds all LogMiner privileges required by Debezium).
-- Oracle XE 11g uses 'XE' as the default SID/service name.
-- =============================================================================

-- Enable ARCHIVELOG mode so Debezium / LogMiner can read the redo logs
-- (Oracle XE 11g must be mounted before ALTER DATABASE can be issued)
SHUTDOWN IMMEDIATE;
STARTUP MOUNT;
ALTER DATABASE ARCHIVELOG;
ALTER DATABASE OPEN;

-- Supplemental logging at the database level – required by LogMiner
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA;
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

-- Create a dedicated application schema/user
DEFINE app_user = '&MONITOR_APP_USER'
DEFINE app_pass = '&MONITOR_APP_PASS'

CREATE USER &app_user IDENTIFIED BY &app_pass
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP
    QUOTA UNLIMITED ON USERS;

GRANT CONNECT, RESOURCE TO &app_user;

-- Grant minimum LogMiner privileges (OWASP A01: CWE-250 – least privilege)
-- Only grants required for Debezium CDC, not EXECUTE_CATALOG_ROLE or SELECT ANY TABLE
GRANT SELECT ANY TRANSACTION TO &app_user;
GRANT LOGMINING TO &app_user;
GRANT CREATE SESSION TO &app_user;
GRANT SELECT ON SYS.V_$DATABASE TO &app_user;
GRANT SELECT ON SYS.V_$LOG TO &app_user;
GRANT SELECT ON SYS.V_$LOGFILE TO &app_user;
GRANT SELECT ON SYS.V_$LOGMNR_CONTENTS TO &app_user;
GRANT SELECT ON SYS.V_$ARCHIVED_LOG TO &app_user;
GRANT SELECT ON SYS.V_$TRANSACTION TO &app_user;

-- Switch to the application schema
ALTER SESSION SET CURRENT_SCHEMA = &app_user;

-- =============================================================================
-- Table: LOG_TRAZA
-- Stores application-level error / trace records.  Debezium will capture
-- INSERT operations on this table and publish them to Kafka.
-- =============================================================================
CREATE TABLE &app_user..log_traza (
    id          NUMBER          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    error_code  VARCHAR2(50)    NOT NULL,
    error_msg   VARCHAR2(4000)  NOT NULL,
    severity    VARCHAR2(10)    DEFAULT 'INFO'
                                CHECK (severity IN ('INFO', 'WARNING', 'CRITICAL')),
    source_app  VARCHAR2(100),
    created_at  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Enable row-level supplemental logging for the table (needed by Debezium)
ALTER TABLE &app_user..log_traza ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

-- Seed data – demonstrates the three severity levels
INSERT INTO &app_user..log_traza (error_code, error_msg, severity, source_app)
VALUES ('APP-001', 'Scheduled job completed successfully', 'INFO', 'batch-processor');

INSERT INTO &app_user..log_traza (error_code, error_msg, severity, source_app)
VALUES ('APP-002', 'Connection pool near capacity (85%)', 'WARNING', 'api-gateway');

INSERT INTO &app_user..log_traza (error_code, error_msg, severity, source_app)
VALUES ('APP-003', 'Unable to reach secondary Oracle node', 'CRITICAL', 'data-sync-daemon');

COMMIT;
