-- =============================================================================
-- Monitor Dashboard – Oracle XE 11g Initialisation Script
-- =============================================================================
-- This script is executed by the gvenzl/oracle-xe image entrypoint when the
-- container starts for the first time.  It runs as SYSDBA (the superuser that
-- already holds all LogMiner privileges required by Debezium).
-- Oracle XE 11g uses 'XE' as the default SID/service name.
-- =============================================================================

-- Enable ARCHIVELOG mode so Debezium / LogMiner can read the redo logs
-- (Oracle XE 11g must be mounted before ALTER DATABASE can be issued)
SHUTDOWN IMMEDIATE;
STARTUP MOUNT;
ALTER DATABASE ARCHIVELOG;
ALTER DATABASE OPEN;

-- Supplemental logging at the database level – required by LogMiner
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA;
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

-- Create a dedicated application schema/user
CREATE USER monitor_app IDENTIFIED BY monitor_pass
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP
    QUOTA UNLIMITED ON USERS;

GRANT CONNECT, RESOURCE TO monitor_app;

-- Grant LogMiner privileges to the Debezium connector user
-- (In production, use a dedicated Debezium user instead of SYSTEM)
GRANT EXECUTE_CATALOG_ROLE TO monitor_app;
GRANT SELECT ANY TRANSACTION TO monitor_app;
GRANT SELECT ANY TABLE TO monitor_app;
GRANT LOGMINING TO monitor_app;

-- Switch to the application schema
ALTER SESSION SET CURRENT_SCHEMA = monitor_app;

-- =============================================================================
-- Table: LOG_TRAZA
-- Stores application-level error / trace records.  Debezium will capture
-- INSERT operations on this table and publish them to Kafka.
-- =============================================================================
CREATE TABLE monitor_app.log_traza (
    id          NUMBER          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    error_code  VARCHAR2(50)    NOT NULL,
    error_msg   VARCHAR2(4000)  NOT NULL,
    severity    VARCHAR2(10)    DEFAULT 'INFO'
                                CHECK (severity IN ('INFO', 'WARNING', 'CRITICAL')),
    source_app  VARCHAR2(100),
    created_at  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Enable row-level supplemental logging for the table (needed by Debezium)
ALTER TABLE monitor_app.log_traza ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

-- Seed data – demonstrates the three severity levels
INSERT INTO monitor_app.log_traza (error_code, error_msg, severity, source_app)
VALUES ('APP-001', 'Scheduled job completed successfully', 'INFO', 'batch-processor');

INSERT INTO monitor_app.log_traza (error_code, error_msg, severity, source_app)
VALUES ('APP-002', 'Connection pool near capacity (85%)', 'WARNING', 'api-gateway');

INSERT INTO monitor_app.log_traza (error_code, error_msg, severity, source_app)
VALUES ('APP-003', 'Unable to reach secondary Oracle node', 'CRITICAL', 'data-sync-daemon');

COMMIT;
